### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by kkkkkkk158** [micronDLA/MobileViTv3#6]
I obey the README-training-and-evaluation.md, and I stuck by this step: cvnets-train --common.config-file config/classification/mobilevit_small.yaml --common.results-loc results_mobilevit_small.
it always said: cvnets-train command not found.  what is 'cvnets-train' for?
I'm not familiar with linux, so I'm confused for a long time. Hoping to find the answer. Thanks!

**Comment by shaktiwadekar9** [comment]
As given in our installation instructions, First, you have to download the specific ml-cvnets (links given), second, replace the files in the downloaded repo, and third, install this modified repo with instructions given in the downloaded repo.
I think you might have missed the installation step. 
Command not found error generally happens if the repo is not installed or if the installation location is different.
Try to install this in a conda environment and test in it.
